import { queryLimits } from '../../contracts/offer-query.js';
const columnDescription = (name: string): string => ({ industry: 'Published company_type; stated then listing', duration: 'Published engagement_length; stated then listing', role: 'Published stated title, then board-authored listing title; no slug/AI fallback', description: 'Stored source text; never AI analysis', salary_text: 'Published salary text; structured alternatives live in offer_salaries', disposition: 'Captured application state, not verified source availability', activity_status: 'Source activity evidence: active, inactive, or unknown; not the user disposition', activity_reason: 'Why the source activity state was assigned', publication_precision: 'instant, date, or unknown; preserves source timestamp precision', location_key: 'Normalized published location: NFKD, lowercase, strip marks, ł→l', company_key: 'Normalized published company', min_amount: 'Lower published salary bound, without unit or tax conversion', max_amount: 'Upper published salary bound, without unit or tax conversion', period: 'hour/day/month/year or NULL; never guessed', normalized_skill: 'Normalized published tag; punctuation retained', evidence_id: 'Immutable source evidence identity', opportunity_id: 'Captured shared vacancy identity; COUNT(DISTINCT opportunity_id) counts unique jobs', offer_id: 'Stable source listing identity', search_rank: 'Zero-based persisted discovery order; NULL for legacy/global catalogue evidence', match_tier: 'Deterministic qualification tier', match_reasons_json: 'JSON array of source-backed qualification reasons', match_origin: 'live or cache origin for this accepted membership', match_policy_version: 'Version of the matching policy that accepted this result' } as Record<string, string>)[name] ?? (name.endsWith('_at') ? 'Captured timestamp in UTC milliseconds (source posted_at/valid_through remain text)' : 'Published or captured field; missing values are NULL; see mapping and enums');
const columns = (text: string) => text.split(' ').map(part => { const [name, type] = part.split(':'); return { name: name!, type: type === 'I' ? 'INTEGER' : type === 'R' ? 'REAL' : 'TEXT', nullable: !['offer_id', 'evidence_id', 'description'].includes(name!), description: columnDescription(name!) }; });
export const queryTables = {
    offers: columns('offer_id opportunity_id evidence_id search_rank:I match_tier match_reasons_json match_origin match_policy_version source url role company location work_mode seniority salary_text contract_type employment_type industry company_size start_date duration description posted_at publication_precision valid_through details_fetched_at:I first_seen_at:I last_seen_at:I activity_status activity_reason activity_checked_at:I disposition listing_title title_source company_key location_key'),
    offer_salaries: columns('offer_id alternative_id min_amount:R max_amount:R currency period contract_type tax_basis raw_text evidence_id parse_status'),
    offer_skills: columns('offer_id skill normalized_skill evidence_id'),
    offer_fact_sources: columns('offer_id field source_kind evidence_id fetched_at:I'),
    offer_extracted_facts: columns('offer_id criterion_key value_text value_number:R value_boolean:I status evidence_quote source_hash extracted_at:I extractor_version stale:I criterion_hash criterion_question value_type model_version evidence_id'),
    offer_text_fts: columns('offer_id text')
};
export const queryFunctions = ['count', 'sum', 'avg', 'min', 'max', 'total', 'coalesce', 'ifnull', 'nullif', 'length', 'substr', 'substring', 'trim', 'ltrim', 'rtrim', 'round', 'abs', 'lower', 'upper', 'like', 'glob', 'json_extract', 'json_valid', 'json_type', 'match', 'bm25'];
export const defaultOfferSql = 'SELECT o.* FROM offers AS o ORDER BY o.search_rank, o.offer_id';
export const querySchema = () => ({ schemaVersion: 1, normalizationVersion: 2, projectionVersion: 2, opportunityGrouping: true, relations: queryTables, functions: queryFunctions, limits: queryLimits, examples: [defaultOfferSql, "SELECT count(DISTINCT opportunity_id) AS opportunities FROM offers", "SELECT offer_id FROM offer_text_fts WHERE offer_text_fts MATCH :term"], enums: { work_mode: ['remote', 'hybrid', 'onsite'], contract_type: ['B2B', 'UoP', 'UoZ', 'UoD'], period: ['hour', 'day', 'month', 'year'], activity_status: ['active', 'inactive', 'unknown'], publication_precision: ['instant', 'date', 'unknown'], disposition: ['active', 'dismissed', 'applied', 'expired'] }, semantics: { extractedFacts: 'Separate AI evidence, not published truth. Match criterion_hash, status=stated and stale=0; not_stated/ambiguous have NULL values. Multiple model/definition versions may exist; use EXISTS to avoid duplicate offers. Quotes are checked and model-verified, not guaranteed correct.', missing: 'NULL; description defaults to empty string', salary: 'Published alternatives only; no currency, period or tax conversion', industry: 'stated.company_type, then listing.company_type', duration: 'stated.engagement_length, then listing.engagement_length', activity: 'Source evidence only. Unknown is retained and is not a claim that applications are open.', precedence: 'Published stated then listing; never canonical or analysis fallback', normalization: 'NFKD, lowercase, strip combining marks, ł→l; technical punctuation preserved', syntax: 'One SELECT or nonrecursive WITH SELECT. No writes, private/system relations, database qualifiers, recursive CTEs or unsupported functions.', timestamps: 'UTC epoch milliseconds; posted_at preserves source text and publication_precision', scope: 'Public accepted saved Discover membership; unknown review membership is excluded' } });
export const queryDdl = Object.entries(queryTables).filter(([n]) => n !== 'offer_text_fts').map(([name, cols]) => `CREATE TABLE ${name} (${cols.map(c => `${c.name} ${c.type}`).join(',')});`).join('\n') + `
CREATE UNIQUE INDEX offer_identity ON offers(offer_id);
CREATE INDEX offer_modes ON offers(work_mode,source);
CREATE INDEX salary_lookup ON offer_salaries(offer_id,currency,period,contract_type);
CREATE INDEX skill_lookup ON offer_skills(normalized_skill,offer_id);
CREATE VIRTUAL TABLE offer_text_fts USING fts5(offer_id UNINDEXED,text,tokenize='unicode61 remove_diacritics 2 tokenchars ''+#.''');`;
